### ISSUE TITLE
The theme's bold feature has no effect.

### ISSUE THREAD

**Issue by AlfredWoods** [ElsaTam/obsidian-fancy-a-story#12]
The theme's bold feature has no effect.

**Comment by ElsaTam** [comment]
Hi @AlfredWoods , thanks for reporting. Sorry you're having issues.
I tried on a sandbox vault, and it's working fine.
![image](https://github.com/user-attachments/assets/c1e7ab0d-05da-4258-8713-a002b377bd64)

I have two questions to explore further the issue with you:
- What is your installer version? See the note in the readme, under Installation section
- Are you using a custom font (Settings > Appearance > Text font)? If yes, can you tell which one?

**Comment by AlfredWoods** [comment]
Hi,@ElsaTam,thanks for answering. I am using Simplified Chinese and the default font.
![Snipaste_2024-12-08_10-25-18](https://github.com/user-attachments/assets/3b68f76c-6a8a-494f-9e95-f6489cd2dfbd)
![Snipaste_2024-12-08_10-25-35](https://github.com/user-attachments/assets/cafacdf3-6f25-4849-aac4-a6df57a90519)

**Comment by ElsaTam** [comment]
Thanks!
I see where the issue is. The default font I'm using in my theme doesn't support simplified Chinese characters with weight 500 (which is the current default weight for bold text). But it does support 600. So I've fixed it, but it will be available in the next release.

In the meantime, you can use this simple snippet:
```css
body {
    --bold-modifier: 300;
}
```

I will ping you when the theme's update will be available :)

**Comment by AlfredWoods** [comment]
Thanks! I'm using this simple snippet, which is perfect!

**Comment by ElsaTam** [comment]
@AlfredWoods I released the new update. Please, be aware that it is a major update, hence some features have now changed and the markdown syntax might need to be updated. See the full changelog: https://github.com/ElsaTam/obsidian-fancy-a-story/releases/tag/2.0.0
