### ISSUE TITLE
iOS Mobile File Explorer & Properties Hidden

### ISSUE THREAD

**Issue by KiraGarvinLerman** [ElsaTam/obsidian-fancy-a-story#14]
**Setup**
- OS: iOS 18.1.1
- Obsidian version: 172
- Installer version: 1.7.7
- Theme version: 2.0.0

**Describe the bug**
Unable to swipe left or right to see File Explorer or Properties overlays.  
Instead, a "shadow" hovers over the open note until I tap the note which makes it disappear.

**To Reproduce**
On an iOS phone:
- switch to Fancy-a-Story theme
- swipe from the left side as if to open the file explorer
- tap to clear shadow
- swipe from the right side as if to open the properties view

**Screenshots**
Here is a video recording demonstrating the "minimal" theme vs "fancy-a-story" on mobile:
https://github.com/user-attachments/assets/7c59915d-e0df-443e-baee-17992f3f63e8

**Additional context**
I just found your theme (and love it!) so, unfortunately, I cannot compare to a prior version.

**Comment by ElsaTam** [comment]
Hi! Thanks a lot for reporting.
Sorry, I don't have an iOS and you are probably the first iOS user to try my theme (or at least take the time to report the issue). I will try to find someone with an iOS among my friends to debug that. Because it works fine on Android. And for what I can tell, your version of iOS is up to date so it should be able to support the [recent features](https://github.com/ElsaTam/obsidian-fancy-a-story/blob/main/css-features.md) I used in the code. But I might have missed one that will break everything.
I need to investigate further and find an iOS. I will let you know how it goes :)

**Comment by KiraGarvinLerman** [comment]
Of course! Let me know if there's anything else I can do to help you troubleshoot.

**Comment by Slootz** [comment]
I actually came to report the exact same issue, also on iOS. Been experiencing it for a few weeks but didn’t (bother to) find the source until now.

(Also, love the theme it’s become a fast favorite <3)

**Comment by ElsaTam** [comment]
@Slootz Thanks for reporting too. The issue is definitively with iOS. I unfortunately didn't find an iOS device to try things out. I will try to ask some help among the other themes dev and see if someone already creating themes can help identify the issue.

**Comment by KiraGarvinLerman** [comment]
Confirming that it worked! Thank you!
